# Generated by Django 6.0.1 on 2026-06-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_custamuser_groups_custamuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custamuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="custamuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="custamuser",
            name="user_permissions",
        ),
    ]
