# Generated by Django 6.0.1 on 2026-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="speed",
            field=models.IntegerField(default=50),
        ),
    ]
