# Generated by Django 6.0.1 on 2026-06-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0002_recepies_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recepies",
            old_name="user",
            new_name="User",
        ),
    ]
