# Generated by Django 6.0.1 on 2026-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0003_rename_user_recepies_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recepies",
            name="view_count",
            field=models.IntegerField(default=1),
        ),
    ]
