# Generated by Django 6.0.1 on 2026-06-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0005_department_studentid_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentid",
            name="student_id",
            field=models.CharField(max_length=100),
        ),
    ]
