# Generated by Django 6.0.1 on 2026-06-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0007_subjects_alter_student_options_subjectmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="report_card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_reportcard_generated", models.DateField(auto_created=True)),
                ("student_rank", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Studerntreportcard",
                        to="vegi.student",
                    ),
                ),
            ],
        ),
    ]
