# Generated by Django 6.0.1 on 2026-06-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0008_report_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report_card",
            name="date_of_reportcard_generated",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name="report_card",
            unique_together={("student_rank", "date_of_reportcard_generated")},
        ),
    ]
