# Generated by Django 6.0.1 on 2026-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vegi", "0009_alter_report_card_date_of_reportcard_generated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
